import os.path
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np
from rasterio.rio.options import resolution_opt

np.set_printoptions(precision=3)
import pandas as pd
import base64
import seaborn as sns
from cellbin2.modules.metadata import TechType

class cbMatrix(object):
    """ singel matrix management, generated by cellbin, convert to gef when saving for further read and write """

    def __init__(self, file_path: str,matrix_type=TechType.Transcriptomics):
        """
        :param file_path: cellbin gef file path
        """
        self.file_path = file_path
        self._sn = None
        self._matrix_type = os.path.basename(self.file_path).split(".")[1]
        ### class internal access data
        self._stereo_exp = None  ### raw stereo_exp
        self._cluster_exp = None
        self.matrix_type=matrix_type

    @property
    def raw_data(self):
        if self._stereo_exp is None:
            self._stereo_exp = self.read(self.file_path)
            self._stereo_exp.obs["MID_counts"] = np.asarray(self._stereo_exp.X.sum(axis=1)).flatten()
        return self._stereo_exp

    @property
    def cluster_data(self):
        if self._cluster_exp is None:
            from pathlib import Path
            if self.matrix_type == TechType.Transcriptomics:
                from saw_cellcluster.cell_cluster import cell_cluster
                self._cluster_exp = cell_cluster(
                    gef_file=self.file_path,
                    bin_type='cell_bins',
                    bin_size=1,
                    use_gpu=True,
                    resolution=1.0,
                    marker=True,
                    out_file=Path(os.path.join(os.path.dirname(self.file_path), f'{self._sn}.cellbin.h5ad')),
                )
                # os.path.join(save_path, f"{self.sn}{suffix}_cluster.h5ad")
            elif self.matrix_type == TechType.Protein:
                from saw_proteincellcluster.cell_cluster_protein import cell_cluster_protein
                self._cluster_exp = cell_cluster_protein(
                    gef_file=self.file_path,
                    bin_type='cell_bins',
                    bin_size=1,
                    use_gpu=True,
                    resolution=0.1,
                )
            else:
                raise Exception(f"Unsupported matrix_type: {self.matrix_type}")
        return self._cluster_exp

    @property
    def sn(self):
        if self._sn is None:
            self._sn = self.raw_data.uns.get(
                "sn", os.path.basename(self.file_path).split(".")[0])
        return self._sn

    @property
    def cell_diameter(self):
        if "cell_diameter" not in self.raw_data.obs.columns:
            if "area" not in self.raw_data.obs.columns:
                raise Exception("No area result in .gef")
            resolution = float(self.raw_data.uns.get("resolution", 500))
            self.raw_data.obs["cell_diameter"] = (
                2 * np.sqrt(self.raw_data.obs["area"].to_numpy() / np.pi)
                * resolution / 1000
            )
        return self.raw_data.obs["cell_diameter"]

    @property
    def cell_area(self):
        if "area" not in self.raw_data.obs.columns:
            raise Exception("No area result in .gef")
        return self.raw_data.obs["area"]

    @property
    def cell_n_gene(self):
        if "n_gene" not in self.raw_data.obs.columns:
            X = self.raw_data.X
            if hasattr(X, "getnnz"):
                self.raw_data.obs["n_gene"] = X.getnnz(axis=1)
            else:
                self.raw_data.obs["n_gene"] = np.asarray((X != 0).sum(axis=1)).flatten()
        return self.raw_data.obs["n_gene"]

    @property
    def cell_MID_counts(self):
        if "MID_counts" not in self.raw_data.obs.columns:
            self.raw_data.obs["MID_counts"] = np.asarray(self.raw_data.X.sum(axis=1)).flatten()
        return self.raw_data.obs["MID_counts"]

    def reset(self):
        """
        Release memory
        """
        del self._stereo_exp  ### raw stereo_exp
        del self._cluster_exp

    @property
    def shape(self):
        return self.raw_data.shape

    def read(self, gef_path):
        if gef_path.endswith(".gef"):
            from utils.gef_reader import read_gef
            data = read_gef(gef_path, bin_type="cell_bins")
            data.uns.setdefault("sn", os.path.basename(gef_path).split(".")[0])
            data.uns.setdefault("resolution", 500)
            return data
        elif gef_path.endswith(".h5ad"):
            import anndata as ad
            data = ad.read_h5ad(gef_path)
            data.uns.setdefault("sn", os.path.basename(gef_path).split(".")[0])
            data.uns.setdefault("resolution", 500)
            if "spatial" not in data.obsm and {"x", "y"}.issubset(data.obs.columns):
                data.obsm["spatial"] = np.column_stack([
                    data.obs["x"].to_numpy(), data.obs["y"].to_numpy()])
            return data
        elif gef_path.endswith(".gem") or gef_path.endswith(".txt"):
            raise NotImplementedError(
                ".gem/.txt cellbin matrices are no longer supported; "
                "convert to .gef before calling cbMatrix.read."
            )
        else:
            raise ValueError(f"Unsupported matrix file extension: {gef_path}")

    def get_cellcount(self):
        return self.raw_data.n_obs

    def get_cellarea(self):
        return str(self.raw_data.obs["area"].mean().astype(np.int16)), str(
            self.raw_data.obs["area"].median().astype(np.int16))

    def get_genetype(self):
        return str(self.cell_n_gene.to_numpy().mean().astype(np.int16)), str(
            np.median(self.cell_n_gene.to_numpy()).astype(np.int16))

    def get_MID(self):
        return (str(self.cell_MID_counts.to_numpy().mean().astype(np.int16)),
                str(np.median(self.cell_MID_counts.to_numpy()).astype(np.int16)))

    def get_total_MID(self):
        return self.raw_data.X.sum()

    def get_faction_cell_gene(self, threshod=200):
        return np.sum(self.cell_n_gene.to_numpy() > threshod) / self.get_cellcount()

    def _plt_vio(self, data, title="", xlabel="", color="Blues", save_path=r"./"):
        # fig = plt.figure()
        fig, ax = plt.subplots()
        q1 = data.quantile(0.25)
        q2 = data.quantile(0.50)  # median number
        q3 = data.quantile(0.75)
        iqr = q3 - q1
        data_no_outliers = data[data <= q3 + 2 * iqr]
        sns.violinplot(y=data_no_outliers, color=color, ax=ax)
        ax.set_title(title)
        ax.set_xlabel(xlabel)
        ax.set_ylabel("")
        fig.savefig(save_path)
        plt.close()
        return [str(round(data.min(), 3)), str(round(q1, 3)),
                str(round(q2, 3)), str(round(q3, 3)), str(round(data.max(), 3))]

    def plot_statistic_vio(self, save_path):

        MID_file = os.path.join(save_path, f"MIDCount.png")
        celldiameter_file = os.path.join(save_path, f"CellDiameter.png")
        cellarea_file = os.path.join(save_path, f"CellArea.png")
        genetype_file = os.path.join(save_path, f"GeneType.png")

        celldiameter_data = self._plt_vio(self.cell_diameter,
                                          title="Univariate distribution of Cell Diameter(\xb5m)",
                                          xlabel="Cell Diameter",
                                          save_path=celldiameter_file, color=mcolors.TABLEAU_COLORS["tab:blue"])

        cellarea_data = self._plt_vio(self.cell_area,
                                      title="Univariate distribution of Cell Area(pixel²)",
                                      xlabel="Cell Area",
                                      save_path=cellarea_file, color=mcolors.TABLEAU_COLORS["tab:purple"])

        ngene_data = self._plt_vio(self.cell_n_gene,
                                   title="Univariate distribution of Gene Type",
                                   xlabel="Gene Type",
                                   save_path=genetype_file, color=mcolors.TABLEAU_COLORS["tab:orange"])
        MID_data = self._plt_vio(self.cell_MID_counts,
                                 title="Univariate distribution of MID counts",
                                 xlabel="MID counts",
                                 save_path=MID_file, color=mcolors.TABLEAU_COLORS["tab:green"])

        return {"celldiameter": celldiameter_data, "cellarea": cellarea_data, "genetype": ngene_data, "MID": MID_data}

    def get_cluster_data(self, reset=True):
        adata = self.cluster_data
        _temp_df = pd.DataFrame()
        _temp_df["x"] = np.asarray(adata.obs["x"]).astype(np.uint32)
        _temp_df["y"] = np.asarray(adata.obs["y"]).astype(np.uint32)
        _temp_df["umap_0"] = adata.obsm["X_umap"][:, 0]
        _temp_df["umap_1"] = adata.obsm["X_umap"][:, 1]
        _temp_df["leiden"] = adata.obs["leiden"].astype(str).tolist()
        if reset is True:
            self.reset()
        return _temp_df

    @property
    def celldensity(self, radiu=200):  ## 200 pixel = 100 um
        from scipy.spatial import cKDTree
        position = self.raw_data.obsm["spatial"]
        tree = cKDTree(position)
        nearby_points_count = np.array(
            [len(tree.query_ball_point(point, r=radiu)) - 1 for point in position])
        return nearby_points_count


    def plot_spatail_figure(self, colormin=None, colormax=None, key="celldensity", save_path='./'):
        _temp_df = pd.DataFrame()
        position = self.raw_data.obsm["spatial"]
        _temp_df["x"], _temp_df['y'] = position[:, 0], position[:, 1]
        if key == "celldensity":
            _temp_df["value"] = self.celldensity
            title = "Cells Density"
        elif key == "CellBin_MID_counts":
            _temp_df["value"] = self.cell_MID_counts.to_numpy()
            title = "CellBin Single Cell MID Counts"
        elif key == "Adjusted_Gene_type":
            _temp_df["value"] = self.cell_MID_counts.to_numpy()
            title = "Adjusted Seg Single Cell MID Counts"
        if colormin is not None and colormax is not None:
            scatter = plt.scatter(_temp_df["x"], _temp_df["y"], c=_temp_df["value"], cmap='viridis', s=5,
                                  vmin=colormin, vmax=colormax)
        else:
            scatter = plt.scatter(_temp_df["x"], _temp_df["y"], c=_temp_df["value"], cmap='viridis', s=5)
        plt.title(title)
        plt.xticks([])
        plt.yticks([])
        plt.colorbar()
        color_min, color_max = scatter.get_clim()
        name = "celldensity" if "density" in key else "MID_counts"
        plt.savefig(os.path.join(save_path, name + '.png'))
        plt.close()
        return color_min, color_max

    def write_h5ad(self, save_path: str, tag: str = ""):
        resolution = 1.0
        os.makedirs(save_path, exist_ok=True)
        # suffix = f"_{tag}" if tag else ""
        out_path = os.path.join(save_path, f"{self.sn}.cellbin_{resolution}.h5ad")
        self.cluster_data.write_h5ad(out_path, compression="gzip")

    def write_gef(self, save_path: str):
        raise NotImplementedError(
            "GEF writing is no longer supported via stereopy; "
            "use gefpy.bgef_writer_cy.generate_bgef directly if needed."
        )


class BinMatrix(object):
    def __init__(self, file_path: str, bin_read=100,
                 matrix_type: TechType = TechType.Transcriptomics,
                 cluster_bin_size: int = 50):
        self._file_path = file_path
        self._stereo_exp = None  ### raw stereo_exp
        self._cluster_exp = None
        self._bin_read = bin_read
        self.matrix_type = matrix_type
        self._cluster_bin_size = cluster_bin_size
        self._sn = None

    def reset(self):
        self._stereo_exp = None
        self._cluster_exp = None

    @property
    def stereo_exp(self):
        if self._stereo_exp is None:
            self._stereo_exp = self.read(self._bin_read)
        return self._stereo_exp

    @property
    def sn(self):
        if self._sn is None:
            self._sn = os.path.basename(self._file_path).split(".")[0]
        return self._sn

    @property
    def cluster_data(self):
        if self._cluster_exp is None:
            from pathlib import Path
            if self.matrix_type == TechType.Transcriptomics:
                from saw_cellcluster.cell_cluster import cell_cluster
                self._cluster_exp = cell_cluster(
                    gef_file=self._file_path,
                    bin_type='',
                    bin_size=self._cluster_bin_size,
                    use_gpu=True,
                    resolution=1.0,
                    marker=True,
                    out_file=Path(os.path.join(os.path.dirname(self._file_path), f'{self._sn}.bin{self._cluster_bin_size}.h5ad')),
                )
            elif self.matrix_type == TechType.Protein:
                from saw_proteincellcluster.cell_cluster_protein import cell_cluster_protein
                self._cluster_exp = cell_cluster_protein(
                    gef_file=self._file_path,
                    bin_type='',
                    bin_size=self._cluster_bin_size,
                    use_gpu=True,
                    resolution=0.1,
                )
            else:
                raise Exception(f"Unsupported matrix_type: {self.matrix_type}")
        return self._cluster_exp

    def write_h5ad(self, save_path: str, tag: str = ""):
        resolution = 1.0
        os.makedirs(save_path, exist_ok=True)
        # suffix = f"_{tag}" if tag else ""
        out_path = os.path.join(save_path, f"{self.sn}.bin{self._cluster_bin_size}_{resolution}.h5ad")
        self.cluster_data.write_h5ad(out_path, compression="gzip")

    @property
    def _width_height(self):
        spatial = self.stereo_exp.obsm["spatial"]
        return (int(spatial[:, 0].max()) + 1, int(spatial[:, 1].max()) + 1)

    def read(self, bin_size=100):
        if self._file_path.endswith(".gef"):
            from utils.gef_reader import read_gef
            data = read_gef(self._file_path, bin_type="bins", bin_size=bin_size)
            return data
        raise ValueError(f"Unsupported bin matrix file: {self._file_path}")

    def get_total_MID(self):
        return self.stereo_exp.X.sum()

    @property
    def MID_counts(self):
        return np.asarray(self.stereo_exp.X.sum(axis=1)).flatten()

    def create_heatmap(self, plot_data):
        import io
        heatmap_array= np.zeros(
            (self._width_height[1] // self._bin_read + 1, self._width_height[0] // self._bin_read + 1), dtype=np.uint16)
        df = pd.DataFrame()
        position = self.stereo_exp.obsm["spatial"]
        df["x"], df["y"] = position[:, 0] // self._bin_read, position[:, 1] // self._bin_read
        df["plot_data"] = plot_data
        heatmap_array[df['y'].astype('uint32'), df['x'].astype('uint32')] = df['plot_data'].to_numpy()
        from matplotlib import colors, cm, ticker
        cmap = colors.LinearSegmentedColormap.from_list("stomics_cmap",
                                                        [(0, '#0c3383'), (0.11, '#005ea3'), (0.22, '#0a88ba'),
                                                         (0.33, '#00c199'), (0.44, '#f2d338'), (0.55, '#f6b132'),
                                                         (0.66, '#f28f38'), (0.77, '#f48f38'), (0.88, '#d91e1e'),
                                                         (1.0, '#d91e1e')])
        cmap.set_under('k', alpha=0)
        plt.imsave('./temp.png', heatmap_array, vmin=1, cmap=cmap)

        with open('./temp.png', "rb") as f:
            img_b = f.read()
            b = io.BytesIO(img_b)  ## heatmap img
        os.remove('./temp.png')
        fig, ax = plt.subplots(figsize=(1, 1))
        norm = colors.Normalize(vmin=0, vmax=df['plot_data'].max())
        im = cm.ScalarMappable(norm=norm, cmap=cmap)

        def human_format(num, pos):
            num = float('{:.3g}'.format(num))
            magnitude = 0
            while abs(num) >= 1000:
                magnitude += 1
                num /= 1000.0
            return '{}{}'.format('{:f}'.format(num).rstrip('0').rstrip('.'), ['', 'K', 'M', 'B', 'T'][magnitude])

        cbar = plt.colorbar(im, ax=ax, format=ticker.FuncFormatter(human_format))
        ax.remove()
        plt.savefig('./temp.png', bbox_inches='tight')
        with open('./temp.png', "rb") as f:
            img_c = f.read()
            c = io.BytesIO(img_c)  # color bar
        os.remove('./temp.png')

        return ('data:image/png;base64,{}'.format(base64.b64encode(b.getvalue()).decode()),
                'data:image/png;base64,{}'.format(base64.b64encode(c.getvalue()).decode()))


class MultiMatrix(object):
    """ Joint management of multiple matrices: may be needed """

    def __init__(self, cellbin_path, adjusted_path, tissuegef_path, raw_path, matrix_type: TechType):

        self.cellbin = None
        self.tissuebin = None
        self.rawbin = None
        self.adjustedbin = None
        self.matrix_type = matrix_type

        if not cellbin_path == "":
            self.cellbin = cbMatrix(cellbin_path,matrix_type=self.matrix_type)
        if not tissuegef_path == "":
            self.tissuebin = BinMatrix(tissuegef_path, bin_read=10, matrix_type=self.matrix_type)
        if not raw_path == "":
            self.rawbin = BinMatrix(raw_path, bin_read=10, matrix_type=self.matrix_type)
        if not adjusted_path == "":
            self.adjustedbin = cbMatrix(adjusted_path,matrix_type=self.matrix_type)

    def read(self, file_path: str):
        pass

    def write(self, file_path: str):
        pass

    def print_info(self, ):
        pass


def main():
    path = "Z:\MySyncFiles"
    geffile = os.path.join(path, 'D04167E2.cellbin.txt')
    cb = cbMatrix(geffile)
    print(cb.shape)


if __name__ == '__main__':
    main()
